import { openings } from './openings.js';

const moveSound=new Audio('https://lichess1.org/assets/sound/standard/Move.ogg');

let currentOpening=null,game=new Chess(),board=null,moveIndex=0,moves=[],mistakes=0,streak=0,selectedSquare=null,timerEnabled=false,timerSeconds=0,timerInterval=null,playAsBlack=false,lastMoveFrom=null,lastMoveTo=null;
let currentTheme=localStorage.getItem('theme')||'light',boardTheme=localStorage.getItem('boardTheme')||'brown',pieceTheme=localStorage.getItem('pieceTheme')||'wikipedia';
const pieceThemes={wikipedia:'https://chessboardjs.com/img/chesspieces/wikipedia/{piece}.png',alpha:'https://chessboardjs.com/img/chesspieces/alpha/{piece}.png'};

function getStats(n){const s=JSON.parse(localStorage.getItem('openingStats')||'{}');return s[n]||{bestStarsWhite:0,bestStarsBlack:0,bestTimeWhite:null,bestTimeBlack:null};}
function saveStats(n,st,t,asBlack){const s=JSON.parse(localStorage.getItem('openingStats')||'{}');if(!s[n])s[n]={bestStarsWhite:0,bestStarsBlack:0,bestTimeWhite:null,bestTimeBlack:null};if(asBlack){if(st>s[n].bestStarsBlack)s[n].bestStarsBlack=st;if(!s[n].bestTimeBlack||t<s[n].bestTimeBlack)s[n].bestTimeBlack=t;}else{if(st>s[n].bestStarsWhite)s[n].bestStarsWhite=st;if(!s[n].bestTimeWhite||t<s[n].bestTimeWhite)s[n].bestTimeWhite=t;}localStorage.setItem('openingStats',JSON.stringify(s));checkAchievements(s);}
function getMasteredCount(){return Object.values(JSON.parse(localStorage.getItem('openingStats')||'{}')).filter(x=>x.bestStarsWhite===3&&x.bestStarsBlack===3).length;}
function checkAchievements(s){const a=JSON.parse(localStorage.getItem('achievements')||'[]'),m=Object.values(s).filter(x=>x.bestStarsWhite===3&&x.bestStarsBlack===3).length;if(m===1&&!a.includes('first')){showAchievement('🏆 First Perfect!','Mastered one opening as both colors!');a.push('first');}if(m===10&&!a.includes('ten')){showAchievement('⭐ Rising Star!','10 openings mastered!');a.push('ten');}if(m===50&&!a.includes('fifty')){showAchievement('👑 Master!','50 openings mastered!');a.push('fifty');}if(m===100&&!a.includes('hundred')){showAchievement('🎓 Grandmaster!','ALL 100 mastered!');a.push('hundred');}localStorage.setItem('achievements',JSON.stringify(a));}
function showAchievement(t,x){document.getElementById('achievementTitle').textContent=t;document.getElementById('achievementText').textContent=x;document.getElementById('achievementPopup').classList.add('show');setTimeout(()=>document.getElementById('achievementPopup').classList.remove('show'),5000);}
function applyTheme(){document.documentElement.setAttribute('data-theme',currentTheme);document.getElementById('themeToggle').textContent=currentTheme==='dark'?'☀️ Light':'🌙 Dark';}
function toggleTheme(){currentTheme=currentTheme==='dark'?'light':'dark';localStorage.setItem('theme',currentTheme);applyTheme();}
function cycleBoardTheme(){const t=['brown','blue','green'],i=t.indexOf(boardTheme);boardTheme=t[(i+1)%3];localStorage.setItem('boardTheme',boardTheme);document.getElementById('boardTheme').textContent='Board: '+boardTheme.charAt(0).toUpperCase()+boardTheme.slice(1);applyBoardTheme();}
function applyBoardTheme(){const b=document.getElementById('board');b.className='';b.classList.add('board-'+boardTheme);}
function cyclePieceTheme(){pieceTheme=pieceTheme==='wikipedia'?'alpha':'wikipedia';localStorage.setItem('pieceTheme',pieceTheme);document.getElementById('pieceTheme').textContent='Pieces: '+(pieceTheme==='wikipedia'?'Wiki':'Alpha');if(board){board.destroy();initBoard();board.position(game.fen());}}
function initBoard(){board=Chessboard('board',{draggable:true,position:'start',onDragStart:onDragStart,onDrop:onDrop,onSnapEnd:onSnapEnd,pieceTheme:pieceThemes[pieceTheme],orientation:playAsBlack?'black':'white',moveSpeed:'fast',snapbackSpeed:100,snapSpeed:50,dragThrottleRate:10});applyBoardTheme();setTimeout(()=>document.querySelectorAll('.square-55d63').forEach(sq=>sq.addEventListener('click',onSquareClick)),100);}
function shadowLastMove(f,t){document.querySelectorAll('.last-move-shadow').forEach(el=>el.classList.remove('last-move-shadow'));const fs=document.querySelector('[data-square="'+f+'"]'),ts=document.querySelector('[data-square="'+t+'"]');if(fs)fs.classList.add('last-move-shadow');if(ts)ts.classList.add('last-move-shadow');}
function onSquareClick(e){const sq=e.currentTarget.getAttribute('data-square');if(!sq||!currentOpening||moveIndex>=moves.length)return;if(!selectedSquare){const p=game.get(sq),oc=playAsBlack?'b':'w';if(p&&p.color===oc&&game.turn()===oc){selectedSquare=sq;highlightSquare(sq);showPossibleMovesForPiece(sq);}}else{attemptMove(selectedSquare,sq);clearHighlights();selectedSquare=null;}}
function highlightSquare(sq){clearHighlights();const se=document.querySelector('[data-square="'+sq+'"]');if(se){const h=document.createElement('div');h.className='selected-square';se.appendChild(h);}}
function showPossibleMovesForPiece(sq){game.moves({square:sq,verbose:true}).forEach(m=>{const ts=document.querySelector('[data-square="'+m.to+'"]');if(ts){const i=document.createElement('div');i.className=m.captured?'possible-capture':'possible-move';ts.appendChild(i);}});}
function clearHighlights(){document.querySelectorAll('.selected-square,.possible-move,.possible-capture').forEach(el=>el.remove());}
function onDragStart(src,pce){if(game.game_over()||!currentOpening||moveIndex>=moves.length)return false;const c=pce.search(/^w/)!==-1?'w':'b',oc=playAsBlack?'b':'w';if(c!==oc||game.turn()!==oc)return false;selectedSquare=src;showPossibleMovesForPiece(src);return true;}
function onDrop(src,tgt){clearHighlights();attemptMove(src,tgt);selectedSquare=null;return undefined;}
function onSnapEnd(){board.position(game.fen());}
function attemptMove(src,tgt){if(!currentOpening||moveIndex>=moves.length)return;const tm=game.move({from:src,to:tgt,promotion:'q'});if(!tm){board.position(game.fen());return;}board.position(game.fen());const em=moves[moveIndex];if(src===em.from&&tgt===em.to){moveSound.play().catch(()=>{});shadowLastMove(src,tgt);streak++;updateStreak();moveIndex++;updateProgress();updateMovesNotation();setTimeout(()=>{if(moveIndex>=moves.length)showCompletion();else makeOpponentMove();},300);}else{showWrongMoveEffect(tgt);mistakes++;streak=0;updateStreak();updateStars();document.getElementById('mistakeCount').textContent=mistakes;setTimeout(()=>{game.undo();board.position(game.fen());showCorrectSquareHint(em.to);},600);}}
function makeOpponentMove(){if(moveIndex>=moves.length)return;const oc=playAsBlack?'w':'b';if(game.turn()===oc){const om=moves[moveIndex];setTimeout(()=>{game.move({from:om.from,to:om.to,promotion:'q'});board.position(game.fen());moveSound.play().catch(()=>{});shadowLastMove(om.from,om.to);moveIndex++;updateProgress();updateMovesNotation();setTimeout(()=>{if(moveIndex>=moves.length)showCompletion();else updateMovePrompt();},300);},500);}}
function showWrongMoveEffect(sq){const se=document.querySelector('[data-square="'+sq+'"]');if(se){const f=document.createElement('div');f.className='wrong-move-flash';se.appendChild(f);setTimeout(()=>f.remove(),500);}}
function showCorrectSquareHint(sq){const se=document.querySelector('[data-square="'+sq+'"]');if(se){const h=document.createElement('div');h.className='correct-square-hint';se.appendChild(h);setTimeout(()=>h.remove(),1000);}}
function updateStreak(){const se=document.getElementById('streakCounter');if(streak>0){se.textContent='🔥 '+streak;se.classList.add('show');}else se.classList.remove('show');}
function updateStars(){const stats=getStats(currentOpening.n);const whiteStars=document.querySelectorAll('#starRatingWhite .star'),blackStars=document.querySelectorAll('#starRatingBlack .star');whiteStars.forEach(s=>s.classList.remove('filled'));blackStars.forEach(s=>s.classList.remove('filled'));let currStars=3;if(mistakes>=3)currStars=1;else if(mistakes>=1)currStars=2;if(playAsBlack){for(let i=0;i<currStars;i++)blackStars[i].classList.add('filled');for(let i=0;i<stats.bestStarsWhite;i++)whiteStars[i].classList.add('filled');}else{for(let i=0;i<currStars;i++)whiteStars[i].classList.add('filled');for(let i=0;i<stats.bestStarsBlack;i++)blackStars[i].classList.add('filled');}}
function updateMovePrompt(){if(!currentOpening||moveIndex>=moves.length)return;const m=moves[moveIndex],c=game.turn()==='w'?'White':'Black',yt=(game.turn()==='w'&&!playAsBlack)||(game.turn()==='b'&&playAsBlack);document.getElementById('moveToPlay').textContent=yt?(c+' to play: '+m.san):('Waiting for '+c+'...');}
function updateProgress(){document.getElementById('currentMove').textContent=moveIndex+'/'+moves.length;document.getElementById('progressBar').style.width=(moves.length>0?(moveIndex/moves.length)*100:0)+'%';}
function updateMovesNotation(){const h=game.history(),n=[];for(let i=0;i<h.length;i+=2){const mn=Math.floor(i/2)+1,w=h[i],b=h[i+1]||'';n.push(mn+'. '+w+(b?' '+b:''));}document.getElementById('movesNotation').textContent=n.length>0?n.join(' '):'-';}
function showCompletion(){stopTimer();document.getElementById('completionMessage').classList.add('show');document.getElementById('moveToPlay').textContent='Opening completed! ✓';let st=3;if(mistakes>=3)st=1;else if(mistakes>=1)st=2;const colorText=playAsBlack?'Black':'White';document.getElementById('completionText').textContent=colorText+': '+st+' star'+(st>1?'s':'')+'!'+(timerEnabled?' ('+formatTime(timerSeconds)+')':'');saveStats(currentOpening.n,st,timerSeconds,playAsBlack);updateOverallProgress();updateOpeningBadges();}
function loadOpening(op){currentOpening=op;game=new Chess();moveIndex=0;mistakes=0;streak=0;selectedSquare=null;moves=[];clearHighlights();document.querySelectorAll('.last-move-shadow').forEach(el=>el.classList.remove('last-move-shadow'));op.p.split(/\s+/).forEach(san=>{if(san){const m=game.move(san);if(m)moves.push({from:m.from,to:m.to,san:san});}});game=new Chess();moveIndex=0;board.position('start');board.orientation(playAsBlack?'black':'white');updateMovePrompt();updateProgress();updateMovesNotation();updateStars();updateStreak();document.getElementById('currentOpeningTitle').textContent=op.n;document.getElementById('completionMessage').classList.remove('show');document.getElementById('mistakeCount').textContent='0';if(timerEnabled)startTimer();setTimeout(()=>document.querySelectorAll('.square-55d63').forEach(sq=>{sq.removeEventListener('click',onSquareClick);sq.addEventListener('click',onSquareClick);}),100);if(playAsBlack&&moves.length>0)makeOpponentMove();}
function startTimer(){stopTimer();timerSeconds=0;const st=Date.now();timerInterval=setInterval(()=>{timerSeconds=Math.floor((Date.now()-st)/1000);document.getElementById('timer').textContent=formatTime(timerSeconds);if(timerSeconds>120)document.getElementById('timer').classList.add('warning');},1000);}
function stopTimer(){if(timerInterval){clearInterval(timerInterval);timerInterval=null;}}
function formatTime(s){const m=Math.floor(s/60),sc=s%60;return m+':'+(sc<10?'0':'')+sc;}
function updateOverallProgress(){const m=getMasteredCount();document.getElementById('overallStats').textContent=m+'/100 openings mastered';document.getElementById('overallProgressFill').style.width=(m/100*100)+'%';}
function updateOpeningBadges(){openings.forEach(op=>{const s=getStats(op.n),it=document.querySelector('[data-opening="'+op.n+'"]');if(it){const existing=it.querySelector('.opening-badges');if(existing)existing.remove();if(s.bestStarsWhite===3||s.bestStarsBlack===3){const container=document.createElement('span');container.className='opening-badges';if(s.bestStarsWhite===3){const wb=document.createElement('span');wb.className='opening-badge white-badge';wb.textContent='W★3';container.appendChild(wb);}if(s.bestStarsBlack===3){const bb=document.createElement('span');bb.className='opening-badge black-badge';bb.textContent='B★3';container.appendChild(bb);}it.appendChild(container);}}});}
function searchOpenings(q){const f=openings.filter(op=>op.n.toLowerCase().includes(q.toLowerCase())),l=document.getElementById('openingsList');l.innerHTML='';f.forEach(op=>{const it=document.createElement('div');it.className='opening-item';it.setAttribute('data-opening',op.n);it.textContent=op.n;const s=getStats(op.n);if(s.bestStarsWhite===3||s.bestStarsBlack===3){const container=document.createElement('span');container.className='opening-badges';if(s.bestStarsWhite===3){const wb=document.createElement('span');wb.className='opening-badge white-badge';wb.textContent='W★3';container.appendChild(wb);}if(s.bestStarsBlack===3){const bb=document.createElement('span');bb.className='opening-badge black-badge';bb.textContent='B★3';container.appendChild(bb);}it.appendChild(container);}it.addEventListener('click',()=>{loadOpening(op);document.querySelectorAll('.opening-item').forEach(el=>el.classList.remove('active'));it.classList.add('active');});l.appendChild(it);});}

document.getElementById('themeToggle').addEventListener('click',toggleTheme);
document.getElementById('boardTheme').addEventListener('click',cycleBoardTheme);
document.getElementById('pieceTheme').addEventListener('click',cyclePieceTheme);
document.getElementById('searchBox').addEventListener('input',e=>searchOpenings(e.target.value));
document.getElementById('whiteSide').addEventListener('click',()=>{playAsBlack=false;document.getElementById('whiteSide').classList.add('active');document.getElementById('blackSide').classList.remove('active');if(board)board.orientation('white');if(currentOpening)loadOpening(currentOpening);});
document.getElementById('blackSide').addEventListener('click',()=>{playAsBlack=true;document.getElementById('blackSide').classList.add('active');document.getElementById('whiteSide').classList.remove('active');if(board)board.orientation('black');if(currentOpening)loadOpening(currentOpening);});
document.getElementById('timerToggle').addEventListener('click',function(){timerEnabled=!timerEnabled;this.textContent=timerEnabled?'Timer ON':'Timer OFF';this.classList.toggle('active');if(timerEnabled&&currentOpening)startTimer();else{stopTimer();document.getElementById('timer').textContent='0:00';document.getElementById('timer').classList.remove('warning');}});
document.getElementById('resetBtn').addEventListener('click',()=>{if(currentOpening)loadOpening(currentOpening);});

applyTheme();initBoard();searchOpenings('');updateOverallProgress();